sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t apena/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true apena/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: elasticbeanstalk-us-east-2-285504358899
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

#access_key_id: $AWS_ACCESS_KEY
#secret_access_key: $AWS_SECRET_KEY
